### ISSUE TITLE
ChooseFromMenu not defined

### ISSUE THREAD

**Issue by imnotyours** [joshfarrant/shortcuts-js#119]
/usr/local/bin/node /Users/useraccount/Library/Preferences/WebStorm2018.3/scratches/scratch.js
/Users/useraccount/Library/Preferences/WebStorm2018.3/scratches/scratch.js:19
const actions = [
                ^

ReferenceError: chooseFromMenu is not defined
    at Object.<anonymous> (/Users/useraccount/Library/Preferences/WebStorm2018.3/scratches/scratch.js:19:17)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)

Process finished with exit code 1

**Comment by joshfarrant** [comment]
Could you please post the code you're using? I've just tried locally and it's working for me.

**Comment by xAlien95** [comment]
Hi @imnotyours, have you imported `chooseFromMenu` before using it? Make sure you have the following at top:

```js
const { chooseFromMenu } = require('@joshfarrant/shortcuts-js/actions');
```

If you already imported it correctly, can you share a script that doesn't work?

**Comment by joshfarrant** [comment]
I'm going to close this for now, if you can replicate the issue feel free to post the code here and we can take a look 😃
